Added Rtehink Ledgers to Consulting Services Partners
dltlandscape/dlt-landscape pull request #6
Opened 2021-04-19 21:35 UTC by RethinkLedgers

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/dltlandscape/dlt-landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/dltlandscape/dlt-landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?

2021-04-20 15:30 UTC, alexhq requested changes

2021-04-20 17:30 UTC, RethinkLedgers commented
Fixed the identation


________________________________________________________________________



Bart Cant

Founder and Managing Partner



ReThink Ledgers  - http://www.rtledgers.com

***@***.***

(704) 737 2724

________________________________________________________________________







---- On Tue, 20 Apr 2021 11:30:24 -0400 Alex Marshall ***@***.***> wrote ----




@alexhq requested changes on this pull request.


In https://github.com/dltlandscape/dlt-landscape/pull/6#discussion_r616795296:

> @@ -768,6 +768,12 @@ landscape:
             logo: ntt-data-2.svg
             crunchbase: https://www.crunchbase.com/organization/ntt-data
             project: company
+           - item:


This line is indented too far, it should match the other -item lines

—
You are receiving this because you authored the thread.
Reply to this email directly, https://github.com/dltlandscape/dlt-landscape/pull/6#pullrequestreview-640101705, or https://github.com/notifications/unsubscribe-auth/ARZAZOOVDT7S4CPXQMYVNPTTJWMZBANCNFSM43GX3S3A.

2021-04-21 20:49 UTC, alexhq commented
Thank you, the indentation looks good. Unfortunately the Crunchbase url is now returning as invalid. It looks like it should be https://www.crunchbase.com/organization/rethink-ledgers

2021-04-22 18:54 UTC, duncanjw approved these changes

2021-04-22 19:00 UTC, duncanjw approved these changes

2021-04-22 19:00 UTC, alexhq approved these changes

2021-04-22 19:05 UTC, merged